# Generated by Django 3.1.1 on 2020-11-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='I am a django developer', max_length=500)),
                ('chat_id', models.IntegerField(default=123456789)),
                ('name', models.CharField(default='New User', max_length=150)),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('your_facebook', models.CharField(blank=True, max_length=450)),
                ('your_instagram', models.CharField(blank=True, max_length=450)),
                ('your_twitter', models.CharField(blank=True, max_length=450)),
                ('your_youtube', models.CharField(blank=True, max_length=450)),
                ('your_medium', models.CharField(blank=True, max_length=450)),
                ('your_linkedin', models.CharField(blank=True, max_length=450)),
                ('your_github', models.CharField(blank=True, max_length=450)),
                ('your_organization', models.CharField(blank=True, max_length=150)),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
