# Generated by Django 3.1.1 on 2020-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_id',
            field=models.BigIntegerField(default=12345678910),
        ),
    ]
