# Generated by Django 3.1.1 on 2020-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_github',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
