# Generated by Django 3.1.1 on 2020-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201020_1719'),
        ('users', '0002_profile_your_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_leader',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pending_list',
        ),
        migrations.RemoveField(
            model_name='groupadminmsg',
            name='g_leader',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='gmember',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='loginconfirmcode',
            name='logged_user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupAdminMsg',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='LoginConfirmCode',
        ),
    ]
