# Generated by Django 3.1.1 on 2020-11-29 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20201129_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_with',
            field=models.ManyToManyField(blank=True, related_name='chat_before', to=settings.AUTH_USER_MODEL),
        ),
    ]
