# Generated by Django 3.1.1 on 2020-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description_for_project',
            field=models.CharField(default='This is an awesome project', max_length=100),
        ),
    ]
