# Generated by Django 3.1.1 on 2020-10-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.TextField(help_text='What are the issues about this code?Just address the issue without fix')),
                ('fix', models.TextField(verbose_name='What should be the fix?Provide it here.')),
                ('resolved', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Title of your project', max_length=150)),
                ('project_description', models.TextField(help_text='What is this project about?')),
                ('views', models.IntegerField(blank=True, default=0)),
                ('project_status', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(help_text='Invite other users to help build this project with you.', related_name='wants_to_contribute', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('code', models.TextField(blank=True, help_text="Use this section if you don't have the file to upload")),
                ('code_in_file', models.FileField(blank=True, help_text='you can leave this field empty if you put the code in the code section.', upload_to='project_files')),
                ('approved', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('approves', models.ManyToManyField(related_name='those_who_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_making_contribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.TextField(help_text='What are the issues about this project?Just address the issue without fix')),
                ('fix', models.TextField(verbose_name='What should be the fix?Provide it here.')),
                ('resolved', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('project_with_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mylikes',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='mylikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_author',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_author',
        ),
        migrations.RemoveField(
            model_name='notifyme',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='notifyme',
            name='gpost',
        ),
        migrations.RemoveField(
            model_name='notifyme',
            name='que_id',
        ),
        migrations.RemoveField(
            model_name='notifyme',
            name='tuto_id',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='MyLikes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='issues',
            name='projectF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projectfiles'),
        ),
        migrations.AddField(
            model_name='issues',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
