# Generated by Django 3.1.1 on 2020-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='chat_id',
            field=models.IntegerField(default=123456789),
        ),
    ]
