# Generated by Django 3.1.1 on 2020-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_short_description_for_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_dependencies',
            field=models.CharField(blank=True, default='1.python-decouple 2.django-crispy-form 3.Pillow', help_text='dependencies your project needs or would need,', max_length=500),
        ),
    ]
