# Generated by Django 3.1.1 on 2020-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201122_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyme',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='notifyme',
            name='blog_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
