# Generated by Django 3.1.1 on 2020-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201202_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatters',
            name='private_chat_id',
            field=models.CharField(max_length=400),
        ),
    ]
