# Generated by Django 3.1.1 on 2020-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_privatemessage_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
