# Generated by Django 3.1.1 on 2020-11-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20201025_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImproveTuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_be_modified', models.TextField(help_text='Which or part of this tutorial can be improved or changed?')),
                ('improvement_or_change', models.TextField(help_text='What is your modification?')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('tuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImproveTutoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('improvetutocomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.improvetuto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
