# Generated by Django 3.1.1 on 2020-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201128_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatters',
            name='chatter1_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='chatters',
            name='chatter2_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='chatters',
            name='private_chat_id',
            field=models.BigIntegerField(),
        ),
    ]
