# Generated by Django 3.1.1 on 2020-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_project_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_dependencies',
            field=models.CharField(blank=True, default='1.python-decouple<br/> 2.django-crispy-form 3.Pillow', help_text='like requirements.txt,', max_length=500),
        ),
    ]
