# Generated by Django 3.1.1 on 2020-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_improvetuto_improvetutocomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvetuto',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
