# Generated by Django 3.1.1 on 2020-10-20 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_project_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(help_text='Invite other users to help build this project with you.Hold Ctrl and click to add', related_name='wants_to_contribute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(help_text='Title of your project', max_length=150, unique=True),
        ),
    ]
