# Generated by Django 3.1.1 on 2020-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201202_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='chat_id',
            field=models.CharField(max_length=400),
        ),
    ]
