# Generated by Django 3.1.1 on 2020-11-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201123_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyme',
            name='improvement_id',
        ),
    ]
