# Generated by Django 3.1.1 on 2020-11-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201128_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatters',
            name='chatter1_id',
        ),
        migrations.RemoveField(
            model_name='chatters',
            name='chatter2_id',
        ),
        migrations.AlterField(
            model_name='chatters',
            name='chatter1_user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chatters',
            name='chatter2_user',
            field=models.CharField(max_length=200),
        ),
    ]
