# Generated by Django 3.1.1 on 2020-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_improvetuto_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
        migrations.AddField(
            model_name='improvetuto',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
