# Generated by Django 3.1.1 on 2020-10-20 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20201020_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='approves',
            field=models.ManyToManyField(blank=True, related_name='those_who_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
