# Generated by Django 3.1.1 on 2020-12-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201202_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='allow_any',
            field=models.BooleanField(blank=True, default=False, help_text='allow any user to enter your room without you adding them or using your room key'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Make your room active for communication or inactive for users'),
        ),
    ]
