# Generated by Django 3.1.1 on 2020-11-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201129_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatters',
            old_name='chatter1_user',
            new_name='chatter_users',
        ),
        migrations.RemoveField(
            model_name='chatters',
            name='chatter2_user',
        ),
    ]
