# Generated by Django 3.1.1 on 2020-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201101_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyme',
            name='improvement_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
