# Generated by Django 3.1.1 on 2020-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201205_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyme',
            name='room_slug',
            field=models.CharField(default='some room', max_length=200),
            preserve_default=False,
        ),
    ]
