# Generated by Django 3.1.1 on 2020-11-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201129_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
    ]
