# Generated by Django 3.1.1 on 2020-10-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_projectfiles_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='code_in_file',
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='code',
            field=models.TextField(blank=True, help_text="Use this section if you don't have the file to upload.Leave blank if you have a file."),
        ),
    ]
