# Generated by Django 3.1.1 on 2020-11-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notifyme_improvement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='subtitle',
            field=models.CharField(default='awesome django', max_length=100),
        ),
    ]
