# Generated by Django 3.1.1 on 2020-12-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='key',
        ),
    ]
