# Generated by Django 3.1.1 on 2020-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201023_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='code',
            field=models.TextField(help_text="Use this section if you don't have the file to upload.Leave blank if you have a file."),
        ),
    ]
