# Generated by Django 3.1.1 on 2020-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201021_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectissues',
            name='fix',
            field=models.CharField(help_text='What should be the fix?Provide it here.Should be short', max_length=350),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='issues',
            field=models.CharField(help_text='What are the issues about this project?Just address the issue without fix', max_length=350),
        ),
    ]
