# Generated by Django 3.1.1 on 2020-12-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_chatroom_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='allow_any',
        ),
    ]
