# Generated by Django 3.1.1 on 2020-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201023_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='code',
            field=models.TextField(help_text='Enter your code here.'),
        ),
    ]
