# Generated by Django 3.1.1 on 2020-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201021_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='code',
            field=models.TextField(blank=True, help_text="Use this section if you don't have the file to upload.Leave blank if you have a file."),
        ),
    ]
