# Generated by Django 3.1.1 on 2020-11-05 09:51

import blog.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201105_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, help_text='A photo to illustrate your post.', upload_to='blog_images', validators=[blog.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, help_text='just a photo to simplify what you are teaching.', upload_to='tutorial_images', validators=[blog.validator.validate_file_size]),
        ),
    ]
