# Generated by Django 3.1.1 on 2020-12-06 21:06

import blog.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_chatroom_allow_any'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_logo',
            field=models.ImageField(upload_to='room_pics', validators=[blog.validator.validate_file_size]),
        ),
    ]
