# Generated by Django 3.1.1 on 2020-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201024_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, default='project-logo-default.png', upload_to='project_logos'),
        ),
    ]
