# Generated by Django 3.1.1 on 2020-11-18 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20201105_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
                ('about', models.CharField(blank=True, default='Team work is all we need', max_length=500)),
                ('room_logo', models.ImageField(blank=True, default='room.jpg', upload_to='room_pics')),
                ('is_active', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pending_users', models.ManyToManyField(blank=True, related_name='pending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funny', models.ManyToManyField(blank=True, related_name='funny', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funny', models.ManyToManyField(blank=True, related_name='pfunny', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='plikes', to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='plove', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='improvetuto',
            name='tuto',
        ),
        migrations.RemoveField(
            model_name='improvetuto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='improvetutocomments',
            name='improvetutocomment',
        ),
        migrations.RemoveField(
            model_name='improvetutocomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='ImproveTuto',
        ),
        migrations.DeleteModel(
            name='ImproveTutoComments',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
