# Generated by Django 3.1.1 on 2020-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201118_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_file',
            field=models.FileField(blank=True, upload_to='message_files'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='pmsg_file',
            field=models.FileField(blank=True, upload_to='private_message_files'),
        ),
    ]
