# Generated by Django 3.1.1 on 2020-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_project_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description_for_project',
            field=models.CharField(blank=True, default='This is an awesome project', max_length=100),
        ),
    ]
