# Generated by Django 3.1.1 on 2020-12-07 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201206_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
