# Generated by Django 3.1.1 on 2020-12-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_chatroom_chat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chat_date',
        ),
    ]
