# Generated by Django 3.1.1 on 2020-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201024_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
    ]
