# Generated by Django 3.1.1 on 2020-11-18 08:23

import blog.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20201118_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_logo',
            field=models.ImageField(blank=True, default='room.jpg', upload_to='room_pics', validators=[blog.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_file',
            field=models.FileField(blank=True, upload_to='message_files', validators=[blog.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='pmsg_file',
            field=models.FileField(blank=True, upload_to='private_message_files', validators=[blog.validator.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('blog_pic', models.ImageField(blank=True, upload_to='blogpics', validators=[blog.validator.validate_file_size])),
                ('views', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
