# Generated by Django 3.1.1 on 2020-10-24 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_remove_project_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='allowed only 200 characters', max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tutorial_content', models.TextField(help_text='Type tutorial here')),
                ('views', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('helpful', models.ManyToManyField(blank=True, related_name='helpful', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('loves', models.ManyToManyField(blank=True, related_name='loves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='tutorial issue', max_length=200)),
                ('fix', models.TextField(help_text='Enter fix here')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='issues',
            name='projectF',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='approves',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectissues',
            name='project_with_issue',
        ),
        migrations.RemoveField(
            model_name='projectissues',
            name='user',
        ),
        migrations.DeleteModel(
            name='FixProjectIssue',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFiles',
        ),
        migrations.DeleteModel(
            name='ProjectIssues',
        ),
        migrations.AddField(
            model_name='issuecomments',
            name='issue_to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorialissues'),
        ),
        migrations.AddField(
            model_name='issuecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
