# Generated by Django 3.1.1 on 2020-12-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_chatroom_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.chatroom'),
            preserve_default=False,
        ),
    ]
