# Generated by Django 3.1.1 on 2020-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201121_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyme',
            name='tuto_id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='allow_any',
            field=models.BooleanField(blank=True, default=False, help_text='allow any user to enter your room'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='key',
            field=models.CharField(help_text='protect your room with a key', max_length=100),
        ),
    ]
