# Generated by Django 3.1.1 on 2020-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201024_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, help_text='just a photo to simplify what you are teaching.', upload_to='tutorial_images'),
        ),
    ]
