# Generated by Django 3.1.1 on 2020-12-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_message_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatroom',
            new_name='roomid',
        ),
    ]
