# Generated by Django 3.1.1 on 2020-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201208_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='roomid',
            field=models.IntegerField(),
        ),
    ]
