# Generated by Django 3.1.1 on 2020-10-24 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_tutorial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialissues',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialissues',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='loves',
        ),
        migrations.DeleteModel(
            name='IssueComments',
        ),
        migrations.DeleteModel(
            name='TutorialIssues',
        ),
        migrations.AddField(
            model_name='comments',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tutorial'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
