# Generated by Django 3.1.1 on 2020-12-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='online_users',
        ),
        migrations.AddField(
            model_name='online',
            name='online_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online', to='auth.user'),
            preserve_default=False,
        ),
    ]
