# Generated by Django 3.1.1 on 2020-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201210_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='roomid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
