# Generated by Django 3.1.1 on 2020-12-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_online_roomid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='online_users',
            new_name='online_user',
        ),
    ]
