# Generated by Django 3.1.1 on 2020-12-10 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20201210_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='users_online', to=settings.AUTH_USER_MODEL),
        ),
    ]
