# Generated by Django 3.1.1 on 2020-12-10 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_chatroom_online_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='online_users',
        ),
        migrations.RemoveField(
            model_name='online',
            name='online_user',
        ),
        migrations.AddField(
            model_name='online',
            name='online_user',
            field=models.ManyToManyField(blank=True, related_name='online', to=settings.AUTH_USER_MODEL),
        ),
    ]
